name: Create release

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 10
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 23
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm i

      - name: Build Chrome release
        run: pnpm build:chrome

      - name: Build Firefox release
        run: pnpm build:firefox

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist_chrome/dist_chrome.zip
            dist_firefox/dist_firefox.zip
